app/profile/forms.py
  
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Bio.',validators = [Required()])
    submit = SubmitField('Submit')

app/profile/__init__.py
from flask import Blueprint
profile = Blueprint('profile',__name__)
from . import views,forms,models

app/profile/views.py
from . import profile as p
from flask import render_template,abort,url_for,redirect,request
from app.auth.models import User
from .forms import UpdateProfile
from flask_login import login_required
from .. import db,photos
#profile
@p.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

#photos logic
@p.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('profile.profile',uname=uname))

@p.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update_profile.html',form =form)

app/templates/profile/profile.html
  
{% extends 'base.html'%}

{% block content %}
<br><br><br>
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>
  <div class="col-md-4">
    {% if user.profile_pic_path %}

    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail" style="border-radius: 40%;">

    {%else%}
    <p>No profile picture</p>

    {% endif %}

  </div>
</div>
<style>

</style>
<br><br><br>
<div class="text-center">
<div class="container-fluid">
    <h4>Change photo here</h4>
<div class="card">
{% if user == current_user %}
<form id="form" action="{{url_for('profile.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">

  <input type="file"  name="photo" class="form-control" required><br>
  <input type="submit">
</form>
</div>
</div><br><br>
  {% endif %}

{% if user == current_user %}
   <center><a href="{{url_for('profile.update_profile',uname=user.username)}}">Edit profile</a></center>
{% endif %}
</div>
</div>
   <br><br><br><br>
{% include "footer.html" %}
{% endblock %}

app/templates/profile/update_profile.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}


    <br><br>
  {{wtf.quick_form(form)}}
</div>


{% endblock %}