app/FAQS/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
class ContactForm(FlaskForm):

    name = StringField('Name',validators=[Required("Please enter your name")])
    email = TextAreaField('Text',validators=[Required("Please enter a valid email address")])
    subject = TextAreaField('Text',validators=[Required("Enter a subject")])
    message = TextAreaField('Comment',validators=[Required("Please enter your reason for contact")])
    submit = SubmitField('Submit')

app/FAQS/__init__.py
from flask import Blueprint
faqs = Blueprint('faqs',__name__)
from . import views,forms,models

app/FAQS/views.py
from . import faqs as f
from flask_login import login_required,current_user,session_protected
from .forms import ContactForm
from flask import render_template,abort,redirect,url_for,request,flash,session
@f.route("/faqs")
def bussiness_idea():
    return render_template("FAQS/bussiness.html")


@f.route('/about', methods=['GET', 'POST'])
def about():
    return render_template("FAQS/about.html")


@f.route('/about', methods=['GET', 'POST'])
def contact():
    session['firstname'] = request.form.get('firstname')
    session['lastname'] = request.form.get('lastname')
    session['email'] = request.form.get('email')
    session['subject'] = request.form.get('subject')
    session['message'] = request.form.get('message')
    print(session['firstname'], session['lastname'], session['email'], session['subject'],session['message'])
    if session['firstname'] != None:
        flash(f'Message sent!', 'success')
    return render_template('FAQS/about.html', tilte = 'Contact')

app/templates/FAQS/about.html
{% extends "base.html" %}
{% block content %}
<style>

.contact-section {
	padding-bottom: 94px;
}

.contact-form input {
	width: 100%;
	font-size: 12px;
	font-weight: 600;
	color: #838383;
	border: 0;
	padding-bottom: 14px;
	border-bottom: 2px solid #E7EBED;
	margin-bottom: 25px;
}

.contact-form textarea {
	width: 100%;
	border-bottom: 2px solid #E7EBED;
	font-size: 12px;
	font-weight: 600;
	color: #838383;
	border-left: 0;
	height: 215px;
	border-right: 0;
	border-top: 0;
	resize: none;
	margin-bottom: 40px;
}

.contact-form button {
	color: #1e1e1e;
	background: transparent;
	border: none;
	font-size: 14px;
	font-weight: 600;
	padding: 16px 50px;
	border: 2px solid #1e1e1e;
	border-radius: 50px;
	cursor: pointer;
	text-transform: uppercase;
}

.contact-widget .cw-item {
	margin-bottom: 50px;
}

.contact-widget .cw-item h5 {
	color: #1e1e1e;
	font-weight: 600;
	margin-bottom: 30px;
}

.contact-widget .cw-item ul li {
	color: #838383;
	font-size: 14px;
	font-weight: 500;
	list-style: none;
	line-height: 28px;
}

.map {
	padding-top: 100px;
}

.map iframe {
	width: 100%;
}

/* ---------------------------------- Responsive Media Styles ---------------------------------*/

@media only screen and (min-width: 1500px) and (max-width: 1920px) {
	.inner-header .user-access {
		float: right;
		margin-right: 200px;
	}
	.inner-header .main-menu {
		float: right;
		margin-right: 238px;
	}
}

@media only screen and (min-width: 1200px) and (max-width: 1340px) {
	.inner-header .user-access {
		margin-right: 60px;
	}
	.inner-header .main-menu {
		margin-right: 55px;
	}
}

/* Medium Device : 1280px */

@media only screen and (min-width: 992px) and (max-width: 1199px) {
	.inner-header .main-menu {
		margin-right: 70px;
	}
	.inner-header .main-menu ul li {
		margin-left: 45px;
	}
	.inner-header .user-access {
		display: none;
	}
	.header-info .shipping-chrg {
		margin-right: 10px;
	}
	.lookbok-left {
		padding-top: 0px;
	}
	.lookbok-pic .pic-text {
		font-size: 95px;
		line-height: 68px;
	}
	.social-links a {
		margin-right: 50px;
	}
	.product-content {
		padding-top: 20px;
	}
	.product-content .p-info {
		margin-top: 35px;
	}
	.cart-btn .site-btn.update-btn {
		margin-right: 0;
		padding: 16px 35px;
	}
	.header-info .shipping-chrg p {
		font-size: 13px;
	}
	.logo-section {
		padding: 70px 0;
	}
	.order-table .cart-item p.product-name {
		font-size: 12px;
		font-weight: 600;
		padding-top: 3px;
	}
}

/* Tablet Device : 768px */

@media only screen and (min-width: 768px) and (max-width: 991px) {
	.header-section {
		padding-left: 0;
		padding-right: 0;
	}
	.inner-header .main-menu {
		margin-right: 50px;
	}
	.inner-header .main-menu ul li {
		margin-left: 30px;
	}
	.header-info .shipping-chrg {
		float: none;
		margin-right: 0;
	}
	.header-info .student-disc {
		float: none;
	}
	.header-info .coupon-code {
		float: none;
	}
	.inner-header .user-access {
		display: none;
	}
	.page-add .page-breadcrumb {
		margin-bottom: 20px;
	}
	.lookbok-left {
		margin-bottom: 30px;
	}
	.checkout-form .in-name {
		text-align: left;
	}
	.social-links a {
		margin-right: 15px;
	}
	.social-links a i {
		margin-right: 10px;
	}
	.cart-btn {
		padding: 50px 30px;
	}
	.cart-btn .coupon-input {
		padding-left: 0;
		margin-bottom: 30px;
	}
	.cart-btn .coupon-input input {
		width: 100%;
	}
	.shipping-info .cs-item {
		margin-right: 15px;
	}
	.contact-form {
		margin-bottom: 40px;
	}
	.logo-section {
		padding: 70px 0;
	}
	.lookbok-left {
		padding-top: 0;
	}
}

/* Large Mobile : 480px */

@media only screen and (max-width: 767px) {
	.header-section {
		height: auto;
		padding-bottom: 0;
	}
	.inner-header {
		overflow: hidden;
	}
	.inner-header .user-access {
		margin-right: 10px;
	}
	.slicknav_menu {
		display: block;
		margin-top: 10px;
	}
	.inner-header .header-right {
		margin-right: 20px;
		margin-top: 4px;
	}
	.slicknav_nav ul {
		margin: 0 0 0 0;
	}
	.main-menu {
		display: none;
	}
	.header-section {
		overflow: hidden;
	}
	.single-slider-item h1 {
		font-size: 72px;
	}
	.single-slider-item h2 {
		font-size: 42px;
	}
	.lookbok-left {
		margin-bottom: 30px;
	}
	.contact-form {
		margin-bottom: 40px;
	}
	.newslatter-form form button {
		position: relative;
		margin-top: 15px;
		width: 100%;
	}
	.header-info .shipping-chrg {
		float: none;
		margin-right: 0;
	}
	.header-info .student-disc {
		float: none;
	}
	.header-info .coupon-code {
		float: none;
	}
	.hero-items .owl-nav button[type=button] {
		left: 5px;
	}
	.social-links {
		text-align: center;
	}
	.social-links a {
		margin-right: 20px;
	}
	.social-links a i {
		margin-right: 0;
	}
	.social-links a span {
		display: none;
	}
	.lookbok-pic .pic-text {
		font-size: 115px;
		line-height: 82px;
	}
	.page-add .page-breadcrumb {
		margin-bottom: 20px;
	}
	.cart-table {
		overflow-y: auto;
	}
	.cart-btn {
		padding: 50px 30px;
	}
	.cart-btn .coupon-input {
		padding-left: 0;
		margin-bottom: 30px;
	}
	.cart-btn .coupon-input input {
		width: 100%;
	}
	.shipping-info .cs-item {
		margin-bottom: 15px;
	}
	.total-info .total-table {
		overflow-y: auto;
	}
	.checkout-form .in-name {
		text-align: left;
	}
	.logo-section {
		padding: 70px 0;
	}
	.lookbok-left {
		padding-top: 0;
	}
	.header-info .header-item {
		margin-bottom: 7px;
	}
	.search-model-form input {
		width: 100%;
	}
}

/* Small : 320px */

@media only screen and (max-width: 479px) {
	.header-section {
		padding-left: 0;
		padding-right: 0;
	}
	.inner-header .header-right {
		margin-right: 0;
	}
	.features-box .single-box-item.first-box .box-text {
		right: 9px;
		top: 7px;
	}
	.features-box .single-box-item .box-text h2 {
		font-size: 40px;
	}
	.features-box .single-box-item.first-box .box-text .trend-alert {
		margin-bottom: 7px;
	}
	.features-box .single-box-item.second-box .box-text {
		left: 20px;
		top: 56px;
	}
	.features-box .single-box-item.large-box .box-text {
		left: 20px;
		top: 28px;
	}
	.features-box .single-box-item.large-box .box-text h2 {
		font-size: 40px;
	}
	.product-filter .product-controls li {
		margin-bottom: 10px;
	}
	.section-title h2 {
		font-size: 36px;
	}
	.lookbok-pic img {
		height: auto;
	}
	.lookbok-pic .pic-text {
		font-size: 65px;
		line-height: 47px;
	}
	.social-links a {
		margin-right: 10px;
	}
	.product-content .product-quantity {
		margin-bottom: 15px;
	}
	.cart-btn .coupon-input input {
		width: 100%;
	}
	.cart-btn .site-btn.update-btn {
		margin-right: 0;
	}
	.cart-btn .site-btn.clear-btn {
		margin-bottom: 15px;
	}
	.header-info .header-item img {
		display: block;
	}
	.header-info {
		padding: 10px 0;
	}
}
/* add + remove button */

  
</style>
<!-- Page Add Section Begin -->
<section class="page-add">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <div class="page-breadcrumb">
                    <h2>Contact us<span>.</span></h2>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Page Add Section End -->

<!-- Contact Section Begin -->
<div class="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <form action="{{ url_for('faqs.contact') }}" class="contact-form" method = "POST">
                    <div class="row">
                        <div class="col-lg-6">
                            <input type="text" placeholder="First Name" name="firstname">
                        </div>
                        <div class="col-lg-6">
                            <input type="text" placeholder="Last Name" name="lastname">
                        </div>
                        <div class="col-lg-12">
                            <input type="email" placeholder="E-mail" name="email">
                            <input type="text" placeholder="Subject" name="subject">
                            <textarea placeholder="Message" name="message"></textarea>
                        </div>
                        <div class="col-lg-12 text-right">
                            <button type="submit">Send message</button>
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-3 offset-lg-1">
                <div class="contact-widget">
                    <div class="cw-item">
                        <h5>Location</h5>
                        <ul>
                            <li>Kenya, </li>
                            <li>Nairobi,Prestige</li>
                        </ul>
                    </div>
                    <div class="cw-item">
                        <h5>Phone</h5>
                        <ul>
                            <li>0746262828</li>
                            
                        </ul>
                    </div>
                    <div class="cw-item">
                        <h5>E-mail</h5>
                        <ul>
                            <li>StreetDine@gmail.com</li>
                          
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="map">
            <div class="row">
                <div class="col-lg-12">
                    <!-- <iframe
                        src="https://www.google.com/maps/place/Th%E1%BA%A3o+%C4%90i%E1%BB%81n,+Qu%E1%BA%ADn+2,+H%E1%BB%93+Ch%C3%AD+Minh,+Vi%E1%BB%87t+Nam/@10.809279,106.7266634,15z/data=!3m1!4b1!4m5!3m4!1s0x3175263d580e4583:0x6d25e042c3aed063!8m2!3d10.8064331!4d106.7323097?hl=vi-VN"
                        height="560" style="border:0;" allowfullscreen=""></iframe> -->
                        <iframe src="https://www.google.com/maps/embed?pb=-1.185241,36.885009" width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0"></iframe>    
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/FAQS/bussiness.html
{% extends "base.html" %}
{% block content %}
<link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Gluten:wght@600&family=Kalam&display=swap" rel="stylesheet">
<style>
    .image-class {
        
    }
    .card {
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
  max-width: 300px;
  margin: auto;
  text-align: center;
  font-family: arial;
}

.price {
  color: grey;
  font-size: 22px;
}

.card button {
  border: none;
  outline: 0;
  padding: 12px;
  color: white;
  background-color: #000;
  text-align: center;
  cursor: pointer;
  width: 100%;
  font-size: 18px;
}

.card button:hover {
  opacity: 0.7;
}
</style>
<div
  class="bg-image p-5 text-center shadow-1-strong rounded mb-5 text-white" 
  style="background-image: url('https://media.istockphoto.com/photos/gourmet-chef-cooking-in-a-commercial-kitchen-picture-id866699668?b=1&k=20&m=866699668&s=170667a&w=0&h=yTgInh3AkI4mncMCJ9WYd0h3shy0g0p2R7QVo7O2PgI='); padding: 200px; background-repeat: no-repeat; background-size: cover; width: 100%; height: 100%;"
>
  <h1 class="mb-3 h2" ></h1>
  
  
  <p><button class="header" style="background-color: black; color: white; font-size: 40px; font-family: 'Gluten', cursive;
    ">Career Motivators</button><br> 
  </p>
  </div>
</div>
<!-- Jumbotron -->



<!-- Jumbotron -->
</a>
<br><br><br><br>
<h2 class="text-center" style="color: #0a9396; font-family: 'Gluten', cursive;">Testimonials from experienced chefs</h2><hr>
<br><br>
<div class="container" style="margin-top: 5rem;">
  <div class="row">
    <div class="col-sm-5 col-md-6">
     
        <div class="card">
            <img src="https://media.istockphoto.com/photos/young-businesswoman-standing-in-the-corridor-picture-id1283362093?b=1&k=20&m=1283362093&s=170667a&w=0&h=TrVSAILp38qGk6HYOmrAJrx4S-CDVHFOP0yJy_Uzihg=" alt="Denim Jeans" style="width:100%">
            <h1>Michelle Mwalange</h1>
            <p class="price">Chef,Student</p>
            <p>From cooking pancakes as a young kid to making a career out of it.</p>
            <a href="" style="font-family: 'Gluten', cursive;"><i class="fab fa-whatsapp" style="font-size: 30px;"></i></a>
          </div>
   

    </div>
    <div class="col-sm-5 offset-sm-2 col-md-6 offset-md-0" >
      <!-- Search form -->
      <div class="text-center">
        <div class="card">
            <img src="https://images.unsplash.com/photo-1522529599102-193c0d76b5b6?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8YmxhY2slMjBwZW9wbGV8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" alt="Denim Jeans" style="width:100%">
            <h1>Elvis Muchai</h1>
            <p class="price">Chef,Blogger</p>
            <p>Get to connect with Elvis to bring an insight into the world of culinary</p>
            <a href="" style="font-family: 'Gluten', cursive;"><i class="fab fa-whatsapp" style="font-size: 30px;"></i></a>
          </div>
   


  </div></div>
  </div>
  
  <!--second testimonial-->

  <div class="container" style="margin-top: 5rem;">
    <div class="row">
      <div class="col-sm-5 col-md-6">
       
          <div class="card">
              <img src="https://media.istockphoto.com/photos/preparing-her-favourite-dish-picture-id892674198?b=1&k=20&m=892674198&s=170667a&w=0&h=gLsLMdnGSpAisnnARmwEHC_p_Wcbw0IjrIY5hFzaAzc=" alt="Denim Jeans" style="width:100%">
              <h1>Jane G`ard</h1>
              <p class="price">Chef</p>
              <p>Read on what inspired her to where he is now</p>
              <a href="" style="font-family: 'Gluten', cursive;"><i class="fab fa-whatsapp" style="font-size: 30px;"></i></a>
            </div>
     
  
      </div>
      <div class="col-sm-5 offset-sm-2 col-md-6 offset-md-0" >
        <!-- Search form -->
        <div class="text-center">
          <div class="card">
              <img src="https://media.istockphoto.com/photos/portrait-of-cheerful-mid-adult-black-man-in-casual-clothing-picture-id1265576300?b=1&k=20&m=1265576300&s=170667a&w=0&h=hW1FZPrA_XktOu70WD8dweE2ErDNPAjW1ZjuXpJJz7A=" alt="Denim Jeans" style="width:100%">
              <h1>Travis Odongo</h1>
              <p class="price">Chef,Blogger</p>
              <p>Get to connect with Travis to bring an insight into the world of culinary</p>
              <a href="" style="font-family: 'Gluten', cursive;"><i class="fab fa-whatsapp" style="font-size: 30px;"></i></a>
            </div>
     
  
    </div>
    </div>
    </div>
    </div></div>
    
<br><br><br><br><br><br>
{% include "footer.html" %}
{% endblock %}