app/cart/models.py
from .. import db
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import UserMixin,login_manager
from app.auth.models import User
from datetime import datetime
class Pitch(db.Model):
    __tablename__ = 'pitches'

    id = db.Column(db.Integer,primary_key = True)
    pitch_title = db.Column(db.String)
    pitch_content = db.Column(db.String(1000))
    category = db.Column(db.String)
    posted = db.Column(db.DateTime,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    likes = db.Column(db.Integer)
    dislikes = db.Column(db.Integer)
    
    comments = db.relationship('Comment',backref =  'pitch_id',lazy = "dynamic")

    def __repr__(self):
        return f'User {self.pitch_title}'

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,category):
        pitches = Pitch.query.filter_by(category=category).all()
        return pitches

    @classmethod
    def get_pitch(cls,id):
        pitch = Pitch.query.filter_by(id=id).first()

        return pitch

    @classmethod
    def count_pitches(cls,uname):
        user = User.query.filter_by(username=uname).first()
        pitches = Pitch.query.filter_by(user_id=user.id).all()

        pitches_count = 0
        for pitch in pitches:
            pitches_count += 1

        return pitches_count

class Comment(db.Model):
    __tablename__ = 'comments'

    id = db.Column(db.Integer,primary_key = True)
    comment = db.Column(db.String(1000))
    user_id = db.Column(db.Integer,db.ForeignKey("users.id"))
    pitch = db.Column(db.Integer,db.ForeignKey("pitches.id"))

    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls,pitch):
        comments = Comment.query.filter_by(pitch_id=pitch).all()
        return comments

app/cart/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required
class PitchForm(FlaskForm):

    title = StringField('Sale title',validators=[Required()])
    text = TextAreaField('Text',validators=[Required()])
    category = SelectField('Type',choices=[('drinks','Drinks and beverages'),('fruits','Fruits'),('foreign','Foreign Dishes'), ('traditional', 'Traditional Dishes'), ('snacks', 'Snacks')],validators=[Required()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    text = TextAreaField('Leave a comment:',validators=[Required()])
    submit = SubmitField('Submit')

app/cart/__init__.py
from flask import Blueprint

cart = Blueprint('cart',__name__)
from . import views,forms,models

app/cart/views.py
from . import cart as c
import flask
from flask_login import login_required,current_user
from flask import render_template,abort,redirect,url_for,request
from app.auth.models import Role,User
from app.profile.forms import UpdateProfile
from .. import db,photos
from app.auth.models import User
from .forms import PitchForm,CommentForm
from .models import Pitch,Comment
from app.profile.forms import UpdateProfile



@c.route('/sales/new', methods = ['GET','POST'])
@login_required
def new_pitch():
    pitch_form = PitchForm()
    if pitch_form.validate_on_submit():
        title = pitch_form.title.data
        pitch = pitch_form.text.data
        category = pitch_form.category.data
        
        # Updated pitch instance
        new_pitch = Pitch(pitch_title=title,pitch_content=pitch,category=category,  user=current_user,likes=0,dislikes=0)

        # Save pitch method
        new_pitch.save_pitch()
        return redirect(url_for('main.index'))

    title = 'New pitch'
    return render_template('cart/new_sell.html',title = title,pitch_form=pitch_form )




@c.route('/sales/drinks')
def drinks_sale():

    pitches = Pitch.get_pitches('drinks')

    return render_template("cart/drinks.html", pitches = pitches)
 

@c.route('/sales/fruits')
def fruits_sale():

    pitches = Pitch.get_pitches('fruits')

    return render_template("cart/fruits.html", pitches = pitches)


@c.route('/sales/foreign')
def foreign_sale():

    pitches = Pitch.get_pitches('foreign')

    return render_template("cart/foreign.html", pitches = pitches)



@c.route('/sales/traditional')
def traditional_sale():

    pitches = Pitch.get_pitches('traditional')

    return render_template("cart/traditional.html", pitches = pitches)


@c.route('/sales/snacks')
def snacks():

    pitches = Pitch.get_pitches('snacks')

    return render_template("cart/snacks.html", pitches = pitches)


@c.route('/sales/<int:id>', methods = ['GET','POST'])
def pitch(id):
    pitch = Pitch.get_pitch(id)
    posted_date = pitch.posted.strftime('%b %d, %Y')

    if request.args.get("like"):
        pitch.likes = pitch.likes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))
                                

    elif request.args.get("dislike"):
        pitch.dislikes = pitch.dislikes + 1

        db.session.add(pitch)
        db.session.commit()

        return redirect("/pitch/{pitch_id}".format(pitch_id=pitch.id))

    comment_form = CommentForm()
    if comment_form.validate_on_submit():
        comment = comment_form.text.data

        new_comment = Comment(comment = comment,user = current_user,pitch_id = pitch)

        new_comment.save_comment()


    comments = Comment.get_comments(pitch)

    return render_template("cart/good.html", pitch = pitch, comment_form = comment_form, comments = comments, date = posted_date)

@c.route('/user/<uname>/sales')
def user_pitches(uname):
    user = User.query.filter_by(username=uname).first()
    pitches = Pitch.query.filter_by(user_id = user.id).all()
    pitches_count = Pitch.count_pitches(uname)
    

    return render_template("cart/user_items.html", user=user,pitches=pitches,pitches_count=pitches_count)

app/templates/cart/buy.html
{% extends "base.html" %}
{% block content %}
<div class="container" style= "font-family: 'Gluten', cursive;;">
  <div class="row">
      <div class="col-md-4">
          <div class="well well-lg">
              <h3>Drinks</h3>
              <p>Get yourself something to refreshen your day</p>
              <a href="{{url_for('cart.drinks_sale')}}" class="btn btn-primary -center">View cart</a>
          </div>
      </div>
      <div class="col-md-4">
          <div class="well well-lg">
              <h3>Snacks</h3>
              <p>Looking for fast food?You are in the right place</p>
              <a href="{{url_for('cart.snack')}}" class="btn btn-primary -center">View cart</a>
          </div>
      </div>
      <div class="col-md-4">
          <div class="well well-lg">
              <h3>Traditional Foods</h3>
              <p>Get to enjoy a classic blend of the best cuisines in kenya</p>
              <a href="{{url_for('cart.traditional_sale')}}" class="btn btn-primary -center">View cart</a>
          </div>
      </div>
  </div>
</div>
<div class="container" style= "font-family: 'Gluten', cursive;">
  <div class="row">
      <div class="col-md-4">
          <div class="well well-lg">
              <h3>Foreigh Dishes</h3>
              <p>For those wishing to explore other culinary cultures</p>
              <a href="{{url_for('cart.foreign_sales')}}" class="btn btn-primary -center">View</a>
          </div>
      </div>
      <div class="col-md-4">
          <div class="well well-lg">
              <h3>Fruits</h3>
              <p>Bringing you tropical fruits right at your doorstep</p>
              <a href="{{url_for('cart.fruits_sale')}}" class="btn btn-primary -center">View cart</a>
          </div>
      </div>
{% endblock %}

app/templates/cart/drinks.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">

   <center> <h1>Drinks Sales</h1></center>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>

    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/foreign.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
    <h1>Foreign Foods</h1>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>
<div class="container-fluid" style="background-color: #912F56; ">
    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/fruits.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
   <center><h1>Fruits</h1></center>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>

    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/good.html
{% extends 'base.html'%}
{% import 'macros.html' as macro%}
{% import "bootstrap/wtf.html" as wtf %}

{%block styles%}
    {{ super() }}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gluten:wght@600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
{%endblock%}
<!-- Content block -->
{%block content%}
<style>
    
@import url('https://fonts.googleapis.com/css2?family=Gluten:wght@600&display=swap');
</style>

<div class="container" style="font-family: 'Gluten', cursive;">
    <div class="row">
        <h3>{{pitch.pitch_title}}</h3>
        <hr>
        <p>{{pitch.pitch_content}}</p>
        <span>
        <p>Posted on {{date}} by {{pitch.user.username| capitalize}}</p>
        <a href="/pitch/{{pitch.id}}?like=1">
            <i class="far fa-thumbs-up"></i>
        </a>{{pitch.likes}} <a href="/pitch/{{pitch.id}}?dislike=1">
            <i class="far fa-thumbs-down"></i>
        </a>{{pitch.dislikes}}</span>

    </div>
    <div class="row">
        <h4>Comments</h4>
        <hr>
        {% if current_user.is_authenticated %}
            {{ wtf.quick_form(comment_form) }}
        {%endif%}
        {{macro.displayComments(comments)}}
    </div>

</div>

{%endblock%}

app/templates/cart/new_sell.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content%}


    <div class="container">
        <div class="col-md-12">
            <h3>Create a new sale</h3>
            <hr>
            {{ wtf.quick_form(pitch_form) }}
        </div>

    </div>
  


  </div>
  <br><br><br><br>

{% endblock %}

app/templates/cart/snack.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
   <center><h1>Snacks</h1></center>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>

    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/snacks.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
   <center><h1>Snacks</h1></center>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>

    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/traditional.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{%block content%}
<link href="https://fonts.googleapis.com/css?family=Indie+Flower|Ranga" rel="stylesheet">
   <center><h1>Traditional Foods</h1></center>
</div>
<div class="container" style="font-family: 'Indie+Flower', cursive;">
    <hr>
    <div class="row">
        {{macro.displayPitches(pitches)}}
    </div>
</div>
<br><br><br>

    {% include "footer.html" %}
    </div>
{%endblock%}

app/templates/cart/user_items.html
{% extends 'base.html'%}
{%import 'macros.html' as macro%}

{% block content %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <h3> {{user.username| capitalize}} </h3>
        <hr>
        <!--Display profile photo-->
        <div class="col-md-3">
            <div class="thumbnail">
                {% if user.profile_pic_path %}
                <img class="" src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
                {%else%}
                <p>No profile picture</p>
                {% endif %}
            </div>
        </div>
        <div class="col-md-9">
            <p>Name: {{user.username}}</p>
            <p>No of sales: {{pitches_count}}</p>
           
        </div>
        <div class="row">
            <div class="col-md-12">
              <h3> Sales </h3>
              <hr>
               {{macro.displayPitches(pitches)}}
            </div>
        </div>
    </div>
</div>
{% endblock %}